### ISSUE TITLE
Gradient has outdated direction syntax

### ISSUE THREAD

**Issue by huer12** [swiss/styleguide#631]
The new syntax is 'to top' instead of 'top'
Found in the file 'chosen-theme.scss': 'linear-gradient(top, ..' 
(it should be 'linear-gradient(to top, ..' or to bottom)

**Comment by judos** [comment]
Got the same warning here:
```
WARNING in ./node_modules/swiss-styleguide/build/css/admin.css
(Emitted value instead of an instance of Error) autoprefixer: /.../node_modules/swiss-styleguide/build/css/admin.css:10:4763: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
NonErrorEmittedError: (Emitted value instead of an instance of Error) autoprefixer: /.../node_modules/swiss-styleguide/build/css/admin.css:10:4763: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
    at Object.emitWarning (/.../node_modules/webpack/lib/NormalModule.js:117:16)
    at result.warnings.forEach (/.../node_modules/postcss-loader/lib/index.js:149:49)
    at Array.forEach (<anonymous>)
    at postcss.process.then (/.../node_modules/postcss-loader/lib/index.js:149:27)
    at <anonymous>
 @ multi ./node_modules/primeng/resources/primeng.min.css ./node_modules/font-awesome/css/font-awesome.min.css ./node_modules/swiss-styleguide/build/css/admin.css
```

Can somebody quickly fix this?

**Comment by gillerr** [comment]
Will be solved with the Material Design migration
Issue will be closed
